version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily' # 動作確認したらmonthlyに変える
      time: '22:00'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: '@types/react'
