version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily' # 動作確認したらmonthlyに変える
      time: '22:30'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]